### Create
POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "Joaquin",
  "email": "joaquin.lie@gmail.com",
  "password": "1234",
  "roles": [ "5ffd67703ef5a2a43a4fad2b"]
}

### Update
PUT http://localhost:3000/users/5ffd686f467486a526398e9e
Content-Type: application/json

{
  "name": "Tomas",
  "email": "tomas.lie@gmail.com",
  "password": "1234",
  "roles": ["5ffd6384223b34a3bf0f08b0", "5ffd67703ef5a2a43a4fad2b"]
}

### Get All
GET http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTExMDc3MjMsImV4cCI6MTYxMTEwOTUyMywibmFtZSI6IlRvbWFzIiwicm9sZXMiOlt7ImlzQWN0aXZlIjp0cnVlLCJfaWQiOiI1ZmZkNjM4NDIyM2IzNGEzYmYwZjA4YjAiLCJuYW1lIjoiQURNSU5TIiwiX192IjowfSx7ImlzQWN0aXZlIjp0cnVlLCJfaWQiOiI1ZmZkNjc3MDNlZjVhMmE0M2E0ZmFkMmIiLCJuYW1lIjoiTUVESUMiLCJfX3YiOjB9XX0.IsbxuO_qj8VSP77wwBNugVwhVJHu7hnbKnQeYRGXgDE

### Get One
GET http://localhost:3000/users/5ffa40b87f995f6408b9a628
Content-Type: application/json

### Delete One
DELETE http://localhost:3000/users/5ffa40b87f995f6408b9a628
Content-Type: application/json

### Get Pagination
GET http://localhost:3000/users/page/0