### Create
POST http://localhost:3000/medics/
Content-Type: application/json

{
  "name": "Joaquin",
  "surname": "Antonio",
  "lastname": "Cardenas",
  "dni": "181448369",
  "photo": "photo.png",
  "email": "jcardenas.lie@gmail.com",
  "locations": ["Chile"]
}

### Get All
GET http://localhost:3000/medics/
Content-Type: application/json

### Get One
GET http://localhost:3000/medics/
Content-Type: application/json

### Get Pagination
GET http://localhost:3000/medics/page/0